### ISSUE TITLE
Extend PDBRx to Support Nucleic Acid Segments

### ISSUE THREAD

**Issue by cjeong73** [madscatt/zazzie#111]
I surveyed the capability of pdbrx to work on missing residues in nucleic acid. 

1, pdbrx generated clean output pdb and psf files for double stranded dna (5ju4.pdb) 
[5ju4.pdb.gz](https://github.com/madscatt/zazzie/files/1907900/5ju4.pdb.gz) with HET atoms in default mode.

2. pdbrx default mode worked well with single stranded dna without HET atoms.
[single_strand.pdb.gz](https://github.com/madscatt/zazzie/files/1907904/single_strand.pdb.gz).

3. I added 3 missing residues at the end of the model single strained dna 
[single_strand_missing.pdb.gz](https://github.com/madscatt/zazzie/files/1907912/single_strand_missing.pdb.gz). The default mode ran without error but pdbrx didn't add the missing residues. 
Run in non-default mode failed to read input fasta file (CGTGAATTCACGggg) with an error as below.

####################################################################
Enter filename containing FASTA sequence for segment A: fasta.txt
Traceback (most recent call last):
  File "gui_mimic.py", line 42, in <module>
    scan.main(variables,txtQueue)
  File "/home/cjeong/Nucleotide_pdbrx_results/5JU4/pdbrx/pdb_rx.py", line 59, in main
    self.run_scan()
  File "/home/cjeong/Nucleotide_pdbrx_results/5JU4/pdbrx/pdb_rx.py", line 120, in run_scan
    preprocessor.user_edit_options()
  File "/home/cjeong/Nucleotide_pdbrx_results/5JU4/pdbrx/pdbrx/preprocessor.py", line 738, in user_edit_options
    self.terminal_edit_options()
  File "/home/cjeong/Nucleotide_pdbrx_results/5JU4/pdbrx/pdbrx/preprocessor.py", line 674, in terminal_edit_options
    segname, fasta_sequence)
  File "/home/cjeong/Nucleotide_pdbrx_results/5JU4/pdbrx/pdbrx/preprocessor.py", line 468, in complete_sequence_fasta
    resid = first_resid + position

**Comment by madscatt** [comment]
Take-home from the current Python 3 port audit: this issue is still relevant, but it should be treated as a nucleic-acid support extension rather than only the old Python 2 traceback.

What appears to work today:

- Complete DNA/RNA-like segments can pass through PDBRx far enough for psfgen to produce CHARMM-style PDB/PSF output when the input coordinates are already complete and force-field-compatible.
- PDBScan can represent nucleic residues and report missing residues in at least some cases.

What is not yet safe to assume:

- PDBRx does not currently have a nucleic-acid equivalent of the protein/PyRosetta missing-residue builder. The current structure-builder path is explicitly protein-oriented, so nucleic gaps should not simply be routed through the same PyRosetta completion logic.
- psfgen support for nucleic acids is present in aliases/patches, but PDBRx needs a careful bridge from PDBScan sequence metadata to a psfgen script that can intentionally build missing nucleic residues rather than merely parameterize the coordinates that already exist.
- Internal nucleic-acid gaps are likely a different class of problem from simple terminal additions and may need to remain unsupported with a clear GUI/log message until we can validate a correct builder strategy.

Important naming caution: nucleic acid residue naming must be exact for the CHARMM force field used by psfgen. We should not let one-letter FASTA symbols, PDB residue names, and CHARMM residue names blur together. For example, FASTA `A/C/G/T/U`, PDB-style `DA/DC/DG/DT`, and CHARMM residue names such as `ADE/CYT/GUA/THY/URA` are related but not interchangeable at every stage. Before implementing this, we should survey how FASTA conventions represent DNA vs RNA and then define an explicit, tested translation layer into the CHARMM force-field names used by our topology files.

Suggested careful path:

1. Add small regression fixtures/tests first for complete ssDNA/dsDNA, terminal-missing ssDNA, and at least one unsupported/internal-gap nucleic case.
2. Verify PDBScan metadata after `mol.run_scan()`: `chain_info`, `segname_info`, FASTA display, `missing_resids`, and `seqs_for_completion()` should all agree about the nucleic sequence and missing residues.
3. Harden the FASTA completion utility so failed matches return failure, moltype-specific conversion is explicit, and DNA/RNA naming is tested against CHARMM topology names.
4. Add a PDBRx decision layer: protein gaps may use the protein builder; nucleic terminal additions should use a psfgen-compatible path if validated; unsupported nucleic cases should halt gently with a clear message to `pgui()` and the logger.
5. Only after those tests exist, update psfgen script generation to build full nucleic segments from sequence metadata, apply correct terminal/deoxy patches, read existing coordinates, and let `guesscoord` fill the intended atoms/residues.

I would keep this issue open until we have the test coverage and a verified nucleic-acid path. The current test suite is not deep enough around PDBScan/PDBRx nucleic sequence transfer and psfgen nucleic completion to safely make this change blind.

**Comment by madscatt** [comment]
Follow-up note from commit 9411c4d: the FASTA utility cleanup added explicit protein FASTA-to-residue mapping so protein FASTA symbols such as A/C/G/T now map to ALA/CYS/GLY/THR for protein segments instead of relying on the shared reverse residue dictionary. This was intentionally limited to protein segments. DNA/RNA FASTA naming remains unresolved here: FASTA A/C/G/T/U, PDB-style DA/DC/DG/DT, and CHARMM names such as ADE/CYT/GUA/THY/URA still need a dedicated, tested translation policy before PDBRx supports nucleic-acid completion. In other words, 9411c4d removes one source of accidental protein/nucleic ambiguity but does not close the DNA FASTA/CHARMM naming work tracked by this issue.
