### ISSUE TITLE
Biomt failure PDBScan

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazzie#92]

**Comment by madscatt** [comment]
The attempted fix leads to this new error:

```
Traceback (most recent call last):
  File "gui_mimic_pdbscan.py", line 39, in <module>
    scan.main(variables,txtQueue)
  File "/share/apps/local/anacondaz/lib/python2.7/site-packages/sassie/build/pdbscan/pdb_scan.py", line 59, in main
    self.run_scan()
  File "/share/apps/local/anacondaz/lib/python2.7/site-packages/sassie/build/pdbscan/pdb_scan.py", line 121, in run_scan
    mol.copy_biomt_segments()
  File "/share/apps/local/anacondaz/lib/python2.7/site-packages/sassie/build/pdbscan/pdbscan/scanner.py", line 2319, in copy_biomt_segments
    
KeyError: ''


```

**Comment by madscatt** [comment]
Some files do NOT actually have an empty space, just a comma without anything else on the line.  Altered the code to read:

```
                        content = content.split(":")[1]
                        content = content.replace(' ', '')
                        for chain in content.split(','):
                            if not chain.isspace() and len(chain) > 0:
                                biomt[bm_no]['subdivs'].append(chain.strip())
                                logging.debug('biomt[bm_no] ' + 
                                          biomt[bm_no]['subdivs'][-1])
                            else:
                                logging.debug('chain == empty_space = ' + 
                                                chain)
```

which allows file 7361.pdb to pass (this file is smaller: six chains that allows for a faster test to changes in the code)

**Comment by madscatt** [comment]
2026-05-05 Python 3 port triage: keep open. Active header_reader._parse_biomol_350() still uses the old REMARK 350 chain parsing shape (content[31:].split(',') and chain != ' '), so this old BIOMT parsing concern was not proven fixed by the PDBScan port checkpoint. Representative archived BIOMT fixture testing moved into slow/complex behavior and should be handled in the deferred PDBScan fixture validation pass.

**Comment by madscatt** [comment]
Fixed on dev in commit 9c75a17 (pdbscan: ignore empty biomt chain entries). REMARK 350 chain parsing now splits after the colon, removes spaces, and ignores empty comma fields, so trailing commas no longer add '' to BIOMT subdivisions. Added a focused regression test for the 5712.pdb chain-list shape. Validation: PDBScan short tests passed (18 passed); archived 5712.pdb header parsing now produces no blank BIOMT subdivisions for biomolecules 1 or 2; a minimal read_pdb -> initial_segmentation -> copy_biomt_segments validation on archived 5712.pdb completes with no blank copied subdivisions and no KeyError: ''. Full residue scanning of 5712.pdb is still very slow and remains part of the separate performance/large-fixture follow-up, not this parser bug.
